### PR TITLE
MarkerImageFactory to create data URIs for marker icons.

### PR DESCRIPTION
**Pull request by GeoffCapper**
Allows for end-users to pull images from their own application jars without needing to either re-compile the GMapsFX jar, or use their own custom HTML file. Usage is:

markerOptions.icon(MarkerImageFactory.createMarkerImage("/path/to/my/image.jpg", "jpg"));

Where image.jpg is in one of the jar files supplied by the end-user of the library.

### CODE REVIEW

**Comment by rterp** [comment]
@GeoffCapper this appears to work on Mac, but on Linux (running in VirtualBox), and on Windows 7, the MarkerImage does not appear.  Do you have a Linux and Windows box you can use to confirm this?

**Comment by GeoffCapper** [comment]
I'll have to dig some out in the next couple of days, I've only got Windows 10 running atm. Would there be any difference in the underlying WebKit used on the different JREs? Have you run with the firebug-lite extension running to see if there are any details given there?

**Comment by GeoffCapper** [comment]
@rterp When you have time and inclination could you try the following code to see if the Data URI stuff works on the WebView on those platforms? It should show a rough black polygon in the corner if it's working.
```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javafx.stage.Stage;

/**
 *
 * @author Geoff Capper
 */
public class WebViewDataURI extends Application {

    final String dataURI = "data:image/png;base64,(iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAAAVUlEQVR42q2TQQoAIAgE9/+fLogOUWqTNsdwElZV89EgKgi0FSrL4SILYMvC7LLemXLcIfMrTBFNhfoP8vkKZTuwkgwDc+dM2uaX5J9c2u2qXDrJBB2G+wIbFa98FwAAAABJRU5ErkJggg==)";

    @Override
    public void start(Stage stage) {

        String html = "<html><body><img src=\"" + dataURI + "\" /></body></html>";

        WebView wv = new WebView();
        wv.setPrefSize(300, 300);

        wv.getEngine().loadContent(html);

        Scene s = new Scene(wv);

        stage.setScene(s);
        stage.sizeToScene();
        stage.centerOnScreen();
        stage.show();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

}
```

**Comment by rterp** [comment]
@GeoffCapper  This is what I'm seeing on windows with 1.8_101

image

**Comment by GeoffCapper** [comment]
That would seem to indicate that it's an issue with the platform's support of data URIs in the WebView rather than our use of it. I'm guessing a bug report is in order. Was it the same version of Java on both platforms? The JDK or the JRE?

**Pull request merged**
